CREATE TABLE BEVERAGE (
	description VARCHAR(100) NOT NULL,
	id serial NOT NULL,
	cost DECIMAL NOT NULL,
	CONSTRAINT BEVERAGE_pk PRIMARY KEY (id)
) WITH (
  OIDS=FALSE
);



CREATE TABLE CONDIMENT (
	id serial NOT NULL,
	description VARCHAR(100) NOT NULL,
	cost DECIMAL NOT NULL,
	CONSTRAINT CONDIMENT_pk PRIMARY KEY (id)
) WITH (
  OIDS=FALSE
);



CREATE TABLE ORDERS (
	id serial NOT NULL,
	beverage_id integer NOT NULL,
	bondiment_id integer NOT NULL,
	CONSTRAINT ORDERS_pk PRIMARY KEY (id)
) WITH (
  OIDS=FALSE
);





ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_fk0 FOREIGN KEY (beverage_id) REFERENCES BEVERAGE(id);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_fk1 FOREIGN KEY (bondiment_id) REFERENCES CONDIMENT(id);
